#!/bin/bash

mkdir lib

cd ./external/rl_imgui/

chmod +x premake5

./premake5 gmake

make

cd ../..

cp ./external/rl_imgui/bin/Debug/librlImGui.a ./lib/librlImGui.a

cd ./external/raylib/src

make PLATFORM=PLATFORM_DESKTOP

cd ../../..

cp ./external/raylib/src/libraylib.a ./lib/libraylib.a

cd ./external/enet/

cmake CMakeLists.txt

make

cd ../../

cp ./external/enet/libenet.a ./lib/libenet.a

cp ./make_linux ./Makefile

cd ./external/sphysics/

make

cd ../../

cp ./external/sphysics/libsphysics.a ./lib/libsphysics.a

cd ./external/easy_profiler/

cmake CMakeLists.txt

make

cd ../../

cp ./external/easy_profiler/bin/libeasy_profiler.so ./lib/libeasy_profiler.so

cd ./external/soloud/build/

genie gmake "SOLOUD_NO_OPENAL=1" "SOLOUD_NO_SDL1=1" "SOLOUD_NO_PORTAUDIO=1"

cd gmake

make

cd ../../../..

cp ./external/soloud/lib/libsolouddemocommon_x86_d.a ./lib/


